# For versions before 1.9.0 use apps/v1
apiVersion: apps/v1 
kind: Deployment

# Data that helps  uniquely identify the object (using name, UID and namespace)
metadata:   
  name: nginx
  labels:
    app: nginx

# What state you desire for the object
spec:
  # Tells the deployment to run 3 pods matching the template
  replicas: 1

  # The selector field defines how the deployment finds which pod to manage
  selector:
    matchLabels:
      app: angular-k8s-deployment
  template:
    metadata:
      # Labels are used as identifying attributes for objects such as pods and replication controller.
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2 
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: internal-nginx-service
  # In order to configure load balancers to provide custom configuration we can use Kubernetes annotations 
  annotations:
    # Defines type of load balancer like Network LB or Classic LB
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # Define for cross zone load balancing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    # Defines whether Public or Private Load Balancer used
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name:  nginx app port name
      port:  80
      protocol: TCP
